### ISSUE TITLE
Voltage Supply

### ISSUE THREAD

**Issue by m1geo** [M0WUT/Intermediate_PCBs#1]
I would have all of the supplies regulated, such that the currents don't change with battery flatness.

Otherwise values will be different per board, which could confuse candidates.

You could either create another voltage net, and have a link that selected either regulated 5V or VBatt.

Just a thought.

**Comment by M0WUT** [comment]
True. but running everything off 5V causes issues with the series / parallel LEDs as there is so little voltage left over from 2 in series that the current limiting resistor is tiny. This means when they are in parallel, they draw 50mA each! Calculations of resistance should still give the same answer, regardless of battery voltage (I hope!) and hfe is so poorly defined on the transistor that the marginal effect of the battery being slightly flatter is fine. Will make v1 without and if it needs fixing in v2, I'll re-open the issue.
